spring:
  database:
    url: jdbc:h2:tcp://localhost/~/reward-demo;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #TODO: auto 설정 변경 및 h2 test 환경 설정
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug